kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.15
    volumes:
      - name: deps
        path: /go
    commands:
      - go test -race -v ./... -cover
    when:
      event:
        exclude:
          - tag

  - name: version
    image: node:14.8
    commands:
      - yarn global add semantic-release@17.1
      - semantic-release

    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event:
        exclude:
          - tag

  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
    when:
      event: tag

  - name: release
    image: golang:1.15
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://github.com/goreleaser/goreleaser/releases/download/v0.142.0/goreleaser_Linux_x86_64.tar.gz | tar xzf - -C /tmp
      - /tmp/goreleaser -f "$PWD/.goreleaser.yml"
    when:
      event: tag

volumes:
  - name: deps
    temp: {}