before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - windows
    goarch:
      - amd64
      - i386
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"